--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kyurzburg/AsyncTaskCB
build-by-default: true
branches:
- main
projects:
  AsyncTaskCB:
    path: asynctaskcb
    model: virion
    type: library
...
